// AUTO-GENERATED BY @sidebase/nuxt-auth
import { RouteOptions } from '/Users/hua/Documents/esim/node_modules/@sidebase/nuxt-auth/dist/runtime/types.ts'
declare module 'nitropack' {
  interface NitroRouteRules {
    auth?: RouteOptions
  }
  interface NitroRouteConfig {
    auth?: RouteOptions
  }
}
