// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/Users/hua/Documents/esim/frontend/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
